# Generated by Django 2.2.6 on 2019-11-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191119_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteConfiguration',
            new_name='Site',
        ),
    ]
