# Generated by Django 2.2.6 on 2019-11-20 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20191119_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='SiteConfiguration',
        ),
    ]
